std::string JSON_ITEMS = "[\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101001,\n"
                         "        \"itemClass\": \"BP_Rifle_AKM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AKM\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101003,\n"
                         "        \"itemClass\": \"BP_Rifle_SCAR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SCAR-L\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101004,\n"
                         "        \"itemClass\": \"BP_Rifle_M416_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M416\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101008,\n"
                         "        \"itemClass\": \"BP_Rifle_M762_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M762\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105001,\n"
                         "        \"itemClass\": \"BP_Other_M249_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M249\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105002,\n"
                         "        \"itemClass\": \"BP_Other_DP28_Wrapper_C_1\",\n"
                         "        \"itemName\": \"DP-28\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";


